"""plotten — a grammar-of-graphics plotting library for Python."""

from plotten._aes import Aes, aes
from plotten._labs import Labs, labs
from plotten._plot import Plot, ggplot
from plotten.coords import CoordCartesian, CoordFlip, coord_flip
from plotten.facets import FacetGrid, FacetWrap, facet_grid, facet_wrap
from plotten.geoms import (
    geom_abline,
    geom_area,
    geom_bar,
    geom_boxplot,
    geom_col,
    geom_density,
    geom_errorbar,
    geom_hline,
    geom_histogram,
    geom_label,
    geom_line,
    geom_point,
    geom_ribbon,
    geom_smooth,
    geom_text,
    geom_tile,
    geom_violin,
    geom_vline,
)
from plotten.scales import (
    LegendEntry,
    ScaleColorContinuous,
    ScaleColorDiscrete,
    ScaleContinuous,
    ScaleDiscrete,
    ScaleLog,
    scale_color_continuous,
    scale_color_discrete,
    scale_color_manual,
    scale_fill_manual,
    scale_x_continuous,
    scale_x_discrete,
    scale_x_log10,
    scale_y_continuous,
    scale_y_discrete,
    scale_y_log10,
)
from plotten.themes import Theme, theme_dark, theme_default, theme_minimal

__all__ = [
    "Aes",
    "CoordCartesian",
    "CoordFlip",
    "FacetGrid",
    "FacetWrap",
    "Labs",
    "LegendEntry",
    "Plot",
    "ScaleColorContinuous",
    "ScaleColorDiscrete",
    "ScaleContinuous",
    "ScaleDiscrete",
    "ScaleLog",
    "Theme",
    "aes",
    "coord_flip",
    "facet_grid",
    "facet_wrap",
    "geom_abline",
    "geom_area",
    "geom_bar",
    "geom_boxplot",
    "geom_col",
    "geom_density",
    "geom_errorbar",
    "geom_hline",
    "geom_histogram",
    "geom_label",
    "geom_line",
    "geom_point",
    "geom_ribbon",
    "geom_smooth",
    "geom_text",
    "geom_tile",
    "geom_violin",
    "geom_vline",
    "ggplot",
    "labs",
    "scale_color_continuous",
    "scale_color_discrete",
    "scale_color_manual",
    "scale_fill_manual",
    "scale_x_continuous",
    "scale_x_discrete",
    "scale_x_log10",
    "scale_y_continuous",
    "scale_y_discrete",
    "scale_y_log10",
    "theme_dark",
    "theme_default",
    "theme_minimal",
]
