"""Theme preview — render a standardized sample plot for theme development."""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from plotten._plot import Plot
    from plotten.themes._theme import Theme


def theme_preview(theme_obj: Theme) -> Plot:
    """Build a sample plot that showcases theme elements.

    The returned :class:`~plotten.Plot` exercises titles, subtitles,
    captions, axis labels, tick labels, legends, gridlines, facet
    strips, and multiple geom types so that every visual aspect of
    a theme is visible at a glance.

    Call ``.show()`` to display interactively or ``.save(path)`` to
    write to a file.

    Parameters
    ----------
    theme_obj : Theme
        The theme to preview.

    Returns
    -------
    Plot
        A fully-specified plot ready for rendering.

    Examples
    --------
    >>> from plotten import theme_dark
    >>> from plotten.themes import theme_preview
    >>> theme_preview(theme_dark()).show()  # doctest: +SKIP

    Save to a file for comparison:

    >>> theme_preview(theme_dark()).save("dark_preview.png")  # doctest: +SKIP
    """
    import math

    import pandas as pd

    from plotten._aes import aes
    from plotten._labs import labs
    from plotten._plot import ggplot
    from plotten.facets import facet_wrap
    from plotten.geoms import geom_line, geom_point

    # Sample data: two series across two facets exercises points, lines,
    # color legend, gridlines, facet strips, and axis labels/ticks.
    n = 15
    records = []
    for i in range(1, n + 1):
        records.append(
            {
                "x": i,
                "y": math.sin(i * 0.4) * 3 + 8,
                "group": "Series A",
                "panel": "Panel 1",
            }
        )
        records.append(
            {
                "x": i,
                "y": math.cos(i * 0.4) * 2 + 6,
                "group": "Series B",
                "panel": "Panel 1",
            }
        )
        records.append(
            {
                "x": i,
                "y": (i / n) * 5 + math.sin(i) * 1.5,
                "group": "Series A",
                "panel": "Panel 2",
            }
        )
        records.append(
            {
                "x": i,
                "y": 10 - (i / n) * 4 + math.cos(i) * 1.2,
                "group": "Series B",
                "panel": "Panel 2",
            }
        )

    df = pd.DataFrame(records)

    p = (
        ggplot(df, aes(x="x", y="y", color="group"))
        + geom_point(size=3)
        + geom_line()
        + facet_wrap("panel")
        + labs(
            title="Theme Preview",
            subtitle="A sample plot showcasing theme elements",
            x="X Axis Label",
            y="Y Axis Label",
            caption="Generated by theme_preview()",
            color="Legend",
        )
        + theme_obj
    )

    return p
